gplay-postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false
    - POSTGRES_USER=postgres
    - POSTGRESS_PASSWORD=postgres
    - POSTGRES_DB=gplay
  volumes:
    - gplay-postgres-data:/var/lib/postgresql/data
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

gplay-rabbitmq:
  restart: always
  image: rabbitmq:3-management
  hostname: my-rabbit
  ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15672:15672"
  volumes:
    - gplay-rabbitmq-data:/var/lib/rabbitmq

gplay-crawler:
  restart: always
  image: behren/gplaycrawler
  environment:
    - POSTGRES_HOST=192.168.20.154
    - RABBITMQ_HOST=192.168.20.154
