gplay-postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false
    - POSTGRES_USER=postgres
    - POSTGRESS_PASSWORD=postgres
    - POSTGRES_DB=gplay
  volumes:
    - gplay-postgres-data:/var/lib/postgresql/data
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    
gplay-crawler:
   image: behren/gplaycrawler
   environment:
    - POSTGRES_HOST=192.168.1.250